/*
This module is for UI testing. It currently testing the name of the project to be HIKEN.
To run this file, you need to install the following:
- mocha framework, selenium-webdriver, and chromedriver [path]
*/

// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('testing name', function () {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit()
  })
  it('testing name', async function () {
    await driver.get('https://cpsc-362-group-project.github.io/WebFighter/')
    await driver.manage().window().setRect({ width: 1164, height: 864 })
    assert(await driver.findElement(By.css('h1')).getText() == 'HIKEN')
    assert(await driver.findElement(By.css('h2')).getText() == 'BROWSER BATTLE')
  })
})
